// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggelnzmwgjsnwvzbmrce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZWxuem13Z2pzbnd2emJtcmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTEwNjEsImV4cCI6MjA2NDU4NzA2MX0.R3_vvH97dcp_j-jQyN2XCBFWi2_Zo-Fv94EfXxGJzpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);